/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.InicioSesion;

/**
 *
 * @author Usuario
 */
public class SignUp extends javax.swing.JFrame {

    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        ver2 = new javax.swing.JLabel();
        ocultar2 = new javax.swing.JLabel();
        ver = new javax.swing.JLabel();
        ocultar = new javax.swing.JLabel();
        citybg = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passLabel = new javax.swing.JLabel();
        ConfirmedLabel = new javax.swing.JLabel();
        ConfirmedTxt = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        passTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        SignUpBtn = new javax.swing.JPanel();
        SignUpBtnTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\logo.png"));
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 290, 220));

        ver2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ver2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\ver.png"));
        ver2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ver2MouseClicked(evt);
            }
        });
        bg.add(ver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 50, 50));

        ocultar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ocultar2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\ocultar.png"));
        ocultar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultar2MouseClicked(evt);
            }
        });
        bg.add(ocultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 50, 50));

        ver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ver.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\ver.png"));
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
        });
        bg.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 50));

        ocultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ocultar.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\ocultar.png"));
        ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarMouseClicked(evt);
            }
        });
        bg.add(ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 50));

        citybg.setBackground(new java.awt.Color(0, 134, 190));
        citybg.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Imagenes\\barberia.png"));
        bg.add(citybg, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 300, 500));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 710, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 40));

        title.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        title.setText("CREAR CUENTA");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        userLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        userLabel.setText("USUARIO");
        bg.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        userTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        userTxt.setForeground(new java.awt.Color(204, 204, 204));
        userTxt.setText("Ingrese el nombre de usuario que tendrá");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        bg.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 320, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 310, 20));

        passLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        passLabel.setText("CONTRASEÑA");
        bg.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        ConfirmedLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        ConfirmedLabel.setText("CONFIRMAR CONTRASEÑA");
        bg.add(ConfirmedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        ConfirmedTxt.setForeground(new java.awt.Color(204, 204, 204));
        ConfirmedTxt.setText("●●●●●●●●");
        ConfirmedTxt.setBorder(null);
        ConfirmedTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmedTxtMousePressed(evt);
            }
        });
        bg.add(ConfirmedTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 280, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, 20));

        passTxt.setForeground(new java.awt.Color(204, 204, 204));
        passTxt.setText("●●●●●●●●");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        bg.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 280, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, 20));

        SignUpBtn.setBackground(new java.awt.Color(51, 51, 51));

        SignUpBtnTxt.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        SignUpBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpBtnTxt.setText("CREAR CUENTA");
        SignUpBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SignUpBtnLayout = new javax.swing.GroupLayout(SignUpBtn);
        SignUpBtn.setLayout(SignUpBtnLayout);
        SignUpBtnLayout.setHorizontalGroup(
            SignUpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpBtnLayout.createSequentialGroup()
                .addComponent(SignUpBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SignUpBtnLayout.setVerticalGroup(
            SignUpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(SignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ver2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ver2MouseClicked


    }//GEN-LAST:event_ver2MouseClicked

    private void ocultar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultar2MouseClicked

    }//GEN-LAST:event_ocultar2MouseClicked

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked

    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered

    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited

    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged

    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed

    }//GEN-LAST:event_headerMousePressed

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed

    }//GEN-LAST:event_userTxtMousePressed

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed

    }//GEN-LAST:event_passTxtMousePressed

    private void SignUpBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpBtnTxtMouseClicked


    }//GEN-LAST:event_SignUpBtnTxtMouseClicked

    private void SignUpBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpBtnTxtMouseEntered

    }//GEN-LAST:event_SignUpBtnTxtMouseEntered

    private void SignUpBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpBtnTxtMouseExited

    }//GEN-LAST:event_SignUpBtnTxtMouseExited

    private void ConfirmedTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmedTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmedTxtMousePressed

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_verMouseClicked

    private void ocultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ocultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ConfirmedLabel;
    public javax.swing.JPasswordField ConfirmedTxt;
    public javax.swing.JPanel SignUpBtn;
    public javax.swing.JLabel SignUpBtnTxt;
    public javax.swing.JPanel bg;
    public javax.swing.JLabel citybg;
    public javax.swing.JPanel exitBtn;
    public javax.swing.JLabel exitTxt;
    public javax.swing.JPanel header;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel logo;
    public javax.swing.JLabel ocultar;
    public javax.swing.JLabel ocultar2;
    public javax.swing.JLabel passLabel;
    public javax.swing.JPasswordField passTxt;
    public javax.swing.JLabel title;
    public javax.swing.JLabel userLabel;
    public javax.swing.JTextField userTxt;
    public javax.swing.JLabel ver;
    public javax.swing.JLabel ver2;
    // End of variables declaration//GEN-END:variables
}
